version: "3"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: 'dev'
      POSTGRES_PASSWORD: 'pass'
      POSTGRES_DB: 'local'
    ports:
      - "5432:5432"
    volumes:
      - "./database/init/:/docker-entrypoint-initdb.d"
  unittestdb:
    image: postgres:latest
    environment:
      POSTGRES_USER: 'test'
      POSTGRES_PASSWORD: 'pass'
      POSTGRES_DB: 'local'
    ports:
      - "15432:5432"
    volumes:
      - "./database/init/:/docker-entrypoint-initdb.d"